// angular6/marketplace-with-chat/src/app/products/components/product-page/product-page.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

import Talk from 'talkjs';

import { Product } from 'src/app/shared/models/product.model';
import { ProductService } from 'src/app/core/services/product.service';
import { User } from 'src/app/shared/models/user.model';
import { TalkService } from 'src/app/core/services/talk.service';

@Component({
  selector: 'app-product-page',
  templateUrl: './product-page.component.html',
  styleUrls: ['./product-page.component.css']
})
export class ProductPageComponent implements OnInit {
  product: Product;
  private chatPopup: Talk.Popup;

  constructor(
    private productService: ProductService,
    private talkService: TalkService,
    private route: ActivatedRoute,
    private router: Router) { }

  ngOnInit() { 
    this.productService.getProduct(this.getProductId()).then(product => {
      this.product = product;

      this.preloadChatPopup(product.vendor);
    });
  }

  goToVendorPage(vendor: User) {
    this.router.navigate(['users/' + vendor.id]);
  }

  showChatPopup() {
    this.chatPopup.show();
  }

  private async preloadChatPopup(vendor: User) {
    this.chatPopup = await this.talkService.createPopup(vendor, false);
    this.chatPopup.mount({ show: false });
  }

  private getProductId() {
    return Number(this.route.snapshot.paramMap.get('id'));
  }

}

<div *ngIf="product">
    <div id="product-information-container">
      <div class="row">
          <div class="col-sm-4"></div>
          <div class="col-sm-4">
              <div class="card information-card">
                  <img class="card-img-top product-information-card-img-top img-fluid mx-auto d-block" src="{{product?.pictureUrl}}" alt="product-picture">
                  <div class="card-block">
                      <h4 class="card-title information-card-title">{{product?.name}}</h4>
                      <h5 class="card-title information-card-title">&euro;	{{product?.price}}</h5>
                  </div>
              </div>
          </div>
          <div class="col-sm-4"></div>
      </div>
    </div>

    <hr class="divider">

    <div id="vendor-information-container">
      <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4 container-title">Vendor</div>
            <div class="col-sm-4"></div>
      </div>
      <div class="row">
          <div class="col-sm-4"></div>
          <div class="col-sm-4">
              <div (click)="goToVendorPage(product.vendor)" class="card information-card vendor-information-card">
                  <img class="card-img-top vendor-information-card-img-top img-fluid mx-auto d-block" src="{{product?.vendor?.profilePictureUrl}}" alt="vendor-picture">
                  <div class="card-block">
                      <h4 class="card-title information-card-title">{{product?.vendor?.name}}</h4>
                  </div>
              </div>
              <button type="button" (click)="showChatPopup()" id="chat-btn" [ngStyle]="{'background-color': product?.vendor?.chatPreferences?.chatButtonColorHex}" class="btn btn-primary btn-block">Chat with {{product?.vendor?.username}}</button>
          </div>
          <div class="col-sm-4"></div>
      </div>
    </div>
</div>

// react/marketplace/marketplace-with-chat/src/pages/Product/ProductPage.tsx
import * as React from 'react';

import './styles.css';

import Talk from 'talkjs';

import { Product } from 'src/shared/models/product.model';
import ProductCard, { Size as ProductCardSize } from '../../components/ProductCard/ProductCard';
import UserCard, { Color, Size as UserCardSize } from '../../components/UserCard/UserCard';
import { User } from 'src/shared/models/user.model';
import { addPopup } from 'src/shared/utils/talk.util';

interface DefaultProps { 
  product: Product,
  talkSession: Talk.Session | null,
  talkConversation: Talk.ConversationBuilder | null,
  onVendorClick: (vendor: User) => void
}

class ProductPage extends React.Component<DefaultProps, object> {

  private chatPopup: Talk.Popup;

  handleVendorClick = (vendor: User) => {
    this.props.onVendorClick(vendor);
  }

  handleChatButtonClick = () => {
    if (!this.chatPopup) return;
    
    this.chatPopup.show();
  }

  preloadChatPopup() {
    if (!this.props.talkSession || !this.props.talkConversation) {
      return;
    }

    this.chatPopup = this.props.talkSession.createPopup(this.props.talkConversation);
    this.chatPopup.mount({ show: false });
    addPopup(this.chatPopup);
  }

  componentDidUpdate() {
    this.preloadChatPopup();
  }
    
  public render() {
    const product = this.props.product;

    return (
      <div className="ProductPage">  
        <div id="product-information-container">
          <div className="row">
            <div className="col-sm-4"></div>
            <div className="col-sm-4">
              <ProductCard 
               product={product}
               size={ProductCardSize.Large}
               hoverable={false}
               softEdges={true}
              />
            </div>
            <div className="col-sm-4"></div>
          </div>
        </div>

        <hr className="divider"></hr>

        <div id="vendor-information-container">
          <div className="row">
            <div className="col-sm-4"></div>
            <div className="col-sm-4 container-title">Vendor</div>
            <div className="col-sm-4"></div>
          </div>
          <div className="row">
            <div className="col-sm-4"></div>
            <div className="col-sm-4">
              <UserCard 
               user={product.vendor}
               color={Color.Gray}
               borderless={false}
               onClick={this.handleVendorClick}
               hoverable={true}
               size={UserCardSize.Large}
               displayName={false}
               useBottomMarginForImage={true}
               changeBackgroundColorOnHover={false}
              />

              <button 
                type="button" 
                id="chat-btn" 
                className="btn btn-primary btn-block" 
                onClick={this.handleChatButtonClick}
                style={{backgroundColor: product.vendor.chatPreferences.chatButtonColorHex}}
              >
                Chat with {product.vendor.username}
              </button>
            </div>
            <div className="col-sm-4"></div>
          </div>
        </div>
      </div>
    );
  }
}

export default ProductPage;
